
package com.java.ws.secure;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorIfc", targetNamespace = "http://secure.ws.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorIfc {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.AddResponse")
    @Action(input = "http://secure.ws.java.com/CalculatorIfc/addRequest", output = "http://secure.ws.java.com/CalculatorIfc/addResponse")
    public void add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sub", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.SubResponse")
    @Action(input = "http://secure.ws.java.com/CalculatorIfc/subRequest", output = "http://secure.ws.java.com/CalculatorIfc/subResponse")
    public void sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "div", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.DivResponse")
    @Action(input = "http://secure.ws.java.com/CalculatorIfc/divRequest", output = "http://secure.ws.java.com/CalculatorIfc/divResponse")
    public void div(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "multiply", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://secure.ws.java.com/", className = "com.java.ws.secure.MultiplyResponse")
    @Action(input = "http://secure.ws.java.com/CalculatorIfc/multiplyRequest", output = "http://secure.ws.java.com/CalculatorIfc/multiplyResponse")
    public void multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
